### Send POST request with json body
POST localhost:8080/create-developers
Content-Type: application/json

{
  "memberId" : "Mini",
  "experienceYears" : 12,
  "developerLevel" : "SENIOR",
  "developerSkillType" : "BACK_END",
  "name" : "Mini Lim",
  "age" : 33
}